<template>
    <v-row >
      
    
      <!-- Employees List  -->
      <v-col cols="12" md="4" lg="4" class="pa-0" >
      <EmployeesListTabs :employeeListData="employeeListData" class="" @tabsEmployee="toggleTabs($event)"   />
      </v-col>
      <!-- Customer-Details-Tabs -->
      <v-col cols="12" md="8" lg="8" class="pa-0" >
       <EmpShowApproval  />
       <EmpLeaveDetails v-if="topTabValue == 'all'"  :employeeListData="employeeListData"  :type="topTabValue"  />
       <EmpLeaveDetails v-if="topTabValue == 'letter'" :employeeListData="employeeListData" :type="topTabValue"/>



       <!-- c1 v-if="topTobValue == leaves" -->
       <!-- c2 v-else -->
       </v-col>
    </v-row>
  </template>
  
  <script>
  import '@/assets/scss/_customers.scss'
  import EmployeesListTabs from '~/components/Employees/employeesListTabs.vue'
  import EmpShowApproval from '~/components/Employees/empShowApproval.vue'
  import EmpLeaveDetails from '~/components/Employees/empLeaveDetails.vue'
  
  export default{
    layout: 'dashboard',
    components: {
        EmployeesListTabs,
        EmpShowApproval,
        EmpLeaveDetails,
    },
    data() {
      return {
        topTabValue: 'all',
      
        ShowList: false,
        selectedEmployee: '',
  
        privacyMood: false,
        employeeListData:[
            {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            },  {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Pending', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, {
                emp_name: 'sams',
                emp_status: 'Approved', 
                leave_type: 'Annual Leave',
                letter_type: 'NOC',
                NOC_Options: 'Travel',
                Travel_Date: 'Apr 2, 2022',
                Travel_Reason: 'Training',
                Address_Emirates: 'Dubai',
                Requested_on:'Dec 28,2022',
                Start_Date: 'Dec 29, 2022',
                End_Date: 'Dec 30,2022',
                No_Days:'02',
                ReasonLeave_Category: 'Annual Leave',
                Status_leave: 'PENDING APPROVAL',
                leave_sec: 'Leave',
            }, 
           
        ],
      
      }
    },
    methods: {
        toggleTabs($event) {
            this.topTabValue = $event
            console.log('ggg', this.topTabValue);
        },
      

      showListEmployees() {
        this.ShowList = !this.ShowList
      },   
  
    },
   
    computed: {
  
    },
  
    mounted() {
     
    },
   
   
  }
  </script>
  